### ISSUE TITLE
did not know where to ask this...

### ISSUE THREAD

**Issue by JacobGood1** [antlr/antlr4-cpp#8]
Is this project stalled indefinitely or is there an optimistic future ahead?

**Comment by sharwell** [comment]
Right now probably a bit of both. I work on it from time to time when I get curious about C++ things, but you can see that has only resulted in limited progress over the past couple of years. Whether it's just me or a group of people, the progress on the project is going to be determined by the amount of effort the community decides to put into it. :smile:
